[phases.setup]
cmds = [
  "apt-get update && apt-get install -y git-lfs",
  "git lfs install",
  "git lfs pull"
]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "gunicorn --workers=1 --threads=4 --bind=0.0.0.0:$PORT app:app"
